# Generated by Django 5.1.4 on 2024-12-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerquizquestionanswer',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
