# Generated by Django 5.1.4 on 2025-01-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubmission',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
