# Generated by Django 5.1.4 on 2024-12-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_learnerquizquestionanswer_time_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
