# Generated by Django 5.1.4 on 2025-01-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courselesson_courselessonlecture_courseenrollment_and_more'),
        ('quizzes', '0003_alter_quiz_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courselesson'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
